site_name: SCRYiNG
theme: readthedocs

nav: 
  - Introduction: 'index.md'
  # - API Reference: autoapi/ 

plugins: 
  - search  
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_ignore:
        - '**/ui.py'
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src