site_name: SCRYiNG
theme: readthedocs

nav: 
  - API Reference: autoapi/ 

plugins: 
  - mkdocs-autoapi:
      autoapi_dir: src
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src